### SQL (DATABASE FUNDAMENTALS)
#### GOAL

👉 Today you will learn:

What is SQL
- How databases work
- How to retrieve data like a professional
- Start thinking like backend / data engineer

1. WHAT IS SQL?

👉 SQL = Structured Query Language

👉 Used to:
- Store data
- Retrieve data
- Filter data
- Analyze data

#### REAL LIFE EXAMPLE
Imagine a table:
| id | name    | city      | salary |
|----|---------|-----------|--------|
| 1  | Ali     | Lahore    | 50000  |
| 2  | Sara    | Karachi   | 60000  |
| 3  | Ahmed   | Islamabad | 70000  |

### How to Run SQL in Python (Correct Way)
We use SQLite database inside Python.
### Step 1 — Import SQLite

In [2]:
import sqlite3

### Step 2 — Create Database Connection

In [3]:
conn = sqlite3.connect("company.db")
cursor = conn.cursor()

This creates a small database file in Colab.
### Step 3 — Create Table

In [4]:
cursor.execute("""
CREATE TABLE employees(
    id INTEGER,
    name TEXT,
    salary INTEGER
)
""")

### Step 4 — Insert Data

In [5]:
cursor.execute("INSERT INTO employees VALUES (1,'Ali',50000)")
cursor.execute("INSERT INTO employees VALUES (2,'Ahmed',60000)")
cursor.execute("INSERT INTO employees VALUES (3,'Sara',70000)")

conn.commit()

### Step 5 — NOW Run Your SQL Query

In [6]:
cursor.execute("SELECT * FROM employees")

rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Ali', 50000)
(2, 'Ahmed', 60000)
(3, 'Sara', 70000)

### BASIC SQL COMMAND
#### 1.SELECT (MOST IMPORTANT)
```
SELECT * FROM employees;
```
👉 Meaning:
- Get ALL data
#### 2.SELECT SPECIFIC COLUMN
```
SELECT name, salary FROM employees;
```
#### 3. FILTERING DATA (VERY IMPORTANT)
**WHERE**
```
SELECT * FROM employees
WHERE city = 'Lahore';
```
👉 Only Lahore employees

**MULTIPLE CONDITIONS**
```
SELECT * FROM employees
WHERE salary > 50000 AND city = 'Karachi';
```
#### 4. SORTING DATA
```
SELECT * FROM employees
ORDER BY salary DESC;
```
👉 Highest salary first
### 5. AGGREGATE FUNCTIONS (IMPORTANT)
**COUNT**
```
SELECT COUNT(*) FROM employees;
```
**SUM**
```
SELECT SUM(salary) FROM employees;
```
**AVG**
```
SELECT AVG(salary) FROM employees;
```
#### 6. GROUPING (VERY POWERFUL)
**GROUP BY**
```
SELECT city, SUM(salary)
FROM employees
GROUP BY city;
```
👉 Same as Pandas groupby()

## SQL Project
### STEP 1 — Import SQLite

In [9]:
import sqlite3
import pandas as pd

### STEP 2 — Create Database Connection
This creates a small database inside Colab.

In [10]:
conn = sqlite3.connect("sales.db")
cursor = conn.cursor()

### STEP 3 — Create Sales Table

In [11]:
cursor.execute("""
CREATE TABLE sales(
    id INTEGER,
    product TEXT,
    price INTEGER,
    quantity INTEGER,
    city TEXT
)
""")

### STEP 4 — Insert Sample Data
(We must insert data before running SQL)

In [12]:
cursor.executemany("""
INSERT INTO sales VALUES (?,?,?,?,?)
""",[
(1,"Laptop",80000,1,"Lahore"),
(2,"Mobile",50000,2,"Karachi"),
(3,"Tablet",30000,3,"Lahore"),
(4,"Laptop",80000,1,"Islamabad"),
(5,"Mobile",50000,1,"Lahore")
])

conn.commit()

### TASK 1 — Get All Data

In [13]:
query = "SELECT * FROM sales"
pd.read_sql_query(query, conn)

   id product  price  quantity       city
0   1  Laptop  80000         1     Lahore
1   2  Mobile  50000         2    Karachi
2   3  Tablet  30000         3     Lahore
3   4  Laptop  80000         1  Islamabad
4   5  Mobile  50000         1     Lahore

### TASK 2 — Get Only Product & Price

In [14]:
query = "SELECT product, price FROM sales"
pd.read_sql_query(query, conn)

  product  price
0  Laptop  80000
1  Mobile  50000
2  Tablet  30000
3  Laptop  80000
4  Mobile  50000

### TASK 3 — Sales where city = Lahore

In [15]:
query = """
SELECT * FROM sales
WHERE city = 'Lahore'
"""
pd.read_sql_query(query, conn)

   id product  price  quantity    city
0   1  Laptop  80000         1  Lahore
1   3  Tablet  30000         3  Lahore
2   5  Mobile  50000         1  Lahore

### TASK 4 — Find Total Revenue

Revenue = price × quantity

In [16]:
query = """
SELECT SUM(price * quantity) AS total_revenue
FROM sales
"""
pd.read_sql_query(query, conn)

   total_revenue
0         400000

### TASK 5 — Total Sales by Product (GROUP BY)

In [17]:
query = """
SELECT product, SUM(price * quantity) AS total_sales
FROM sales
GROUP BY product
"""
pd.read_sql_query(query, conn)

  product  total_sales
0  Laptop       160000
1  Mobile       150000
2  Tablet        90000

###  What we learned

I just used SQL inside Python:

| Skill            | Tool                    |
|------------------|-------------------------|
| Database         | SQLite                  |
| SQL execution    | cursor / pandas         |
| Result display   | pandas DataFrame        |

# How SQL Works Inside Python

When we run SQL in Colab, three tools work together:

| Skill            | Tool                 | Role                    |
|------------------|----------------------|-------------------------|
| Database         | SQLite               | Stores data             |
| SQL execution    | cursor / pandas      | Runs SQL queries        |
| Result display   | pandas DataFrame     | Shows results nicely    |

Now understand each step deeply 👇

### 1. Database → SQLite
What is SQLite?

SQLite is a mini database stored in a single file.

Think of it like:

📁 sales.db → inside this file lives your tables.

When we wrote:
```
conn = sqlite3.connect("sales.db")
```
👉 Python created a database file.

Inside this database we created a table:
```
CREATE TABLE sales(...)
```
So now structure is:
```
sales.db
   └── sales table
```
SQLite acts as data storage.

Just like Excel stores data in sheets, SQLite stores data in tables.

### 2. SQL Execution → cursor / pandas

We need a way to send SQL queries to the database.

There are two ways:
### Method A — cursor (raw SQL)
```
cursor.execute("SELECT * FROM sales")
```
Cursor acts like a messenger

It sends SQL commands to the database.

Workflow:

Python → cursor → SQLite → result → Python

But cursor returns data in a messy format (tuples).

**Example output:**
```
[(1,'Laptop',80000,1,'Lahore')]
```
### Method B — pandas (better way)
```
pd.read_sql_query(query, conn)
```
Pandas sends SQL and converts result into table format.

Instead of ugly tuples, you get:

| id | product | price | quantity | city |

Much easier to read and analyze.

So pandas is a smart SQL runner.

### 3. Result Display → Pandas DataFrame
#### What is DataFrame?

A DataFrame is like an Excel sheet in Python.

When we run:
```
pd.read_sql_query(query, conn)
```
The SQL result becomes a DataFrame:
```
   id  product  price  quantity   city
0  1   Laptop   80000      1     Lahore
```
Now you can:
- filter
- analyze
- visualize
- export

This is why DataFrame is powerful
### Complete Flow (Very Important)
```
SQLite (Database)
     ↑
cursor / pandas (run SQL)
     ↑
Pandas DataFrame (show results)
```
## Real-Life Analogy

| Real world        | SQL Project           |
|-------------------|-----------------------|
| Warehouse         | SQLite database       |
| Worker            | Cursor                |
| Manager           | Pandas                |
| Report            | DataFrame             |

How SQL works in Python?
SQLite stores data, cursor or pandas executes SQL queries, and pandas DataFrame displays the results in table format.

# COMPLETE RESULT SUMMARY

| Task                    | SQL Concept Used     |
|-------------------------|----------------------|
| Get all data            | SELECT               |
| Specific columns        | SELECT column        |
| Filtering               | WHERE                |
| Revenue calculation     | SUM()                |
| Business insight        | GROUP BY             |

### SQL vs Pandas
| SQL                                | Pandas Equivalent                    |
|------------------------------------|--------------------------------------|
| SELECT * FROM sales                | df                                   |
| SELECT col                         | df[['col']]                          |
| WHERE city='Lahore'                | df[df.city=='Lahore']                |
| SUM(price*qty)                     | (df.price*df.qty).sum()              |
| GROUP BY product                   | df.groupby('product')                |

#### “What does GROUP BY do?”
GROUP BY groups rows with same values and lets us apply aggregate functions like SUM, COUNT, AVG.