### Advanced Data Analysis
### GOAL

👉 Learn:
- Sorting data
- Advanced filtering
- Extracting insights (VERY IMPORTANT)
- Answering business questions

### Step 1 — Create sales_data.csv inside Colab

In [17]:
import pandas as pd

data = {
    "name": ["Laptop", "Mouse", "Keyboard", "Monitor", None, "Mouse", "Laptop", "Tablet", "Phone", "Headphones"],
    "price": [1200, 25, 45, None, 300, 25, 1200, 400, None, 80],
    "quantity": [1, 2, None, 1, 3, 2, 1, None, 5, 2],
    "city": ["Islamabad","Lahore","Karachi","Islamabad","Lahore","Lahore","Islamabad","Karachi","Islamabad","Lahore"]
}

df = pd.DataFrame(data)

# Save CSV file
df.to_csv("sales_data.csv", index=False)

df

         name   price  quantity       city
0      Laptop  1200.0       1.0  Islamabad
1       Mouse    25.0       2.0     Lahore
2    Keyboard    45.0       NaN    Karachi
3     Monitor     NaN       1.0  Islamabad
4        None   300.0       3.0     Lahore
5       Mouse    25.0       2.0     Lahore
6      Laptop  1200.0       1.0  Islamabad
7      Tablet   400.0       NaN    Karachi
8       Phone     NaN       5.0  Islamabad
9  Headphones    80.0       2.0     Lahore

### Step 2 — Now run YOUR cleaning code

Run this in the next cell:

In [18]:
import pandas as pd

df = pd.read_csv("sales_data.csv")

# Clean data
df["price"].fillna(df["price"].mean(), inplace=True)
df["quantity"].fillna(1, inplace=True)
df = df.drop_duplicates()
df = df.dropna(subset=["name"])

# Create total column
df["total"] = df["price"] * df["quantity"]

df

/tmp/ipykernel_1351/957149856.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["price"].fillna(df["price"].mean(), inplace=True)
/tmp/ipykernel_1351/957149856.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["quantity"].fillna(1, inplace=True)

         name     price  quantity       city     total
0      Laptop  1200.000       1.0  Islamabad  1200.000
1       Mouse    25.000       2.0     Lahore    50.000
2    Keyboard    45.000       1.0    Karachi    45.000
3     Monitor   409.375       1.0  Islamabad   409.375
7      Tablet   400.000       1.0    Karachi   400.000
8       Phone   409.375       5.0  Islamabad  2046.875
9  Headphones    80.000       2.0     Lahore   160.000

### Step 3 — Save the CLEAN dataset (important)

In [19]:
df.to_csv("sales_data_cleaned.csv", index=False)

Now cleaned dataset will exist in Colab files panel

### STEP 4: Sorting Data
#### Sort by Price (High → Low)

In [20]:
sorted_data = df.sort_values(by="price", ascending=False)
print(sorted_data)

         name     price  quantity       city     total
0      Laptop  1200.000       1.0  Islamabad  1200.000
8       Phone   409.375       5.0  Islamabad  2046.875
3     Monitor   409.375       1.0  Islamabad   409.375
7      Tablet   400.000       1.0    Karachi   400.000
9  Headphones    80.000       2.0     Lahore   160.000
2    Keyboard    45.000       1.0    Karachi    45.000
1       Mouse    25.000       2.0     Lahore    50.000

#### Sort by Total Sales

In [21]:
print(df.sort_values(by="total", ascending=False))

         name     price  quantity       city     total
8       Phone   409.375       5.0  Islamabad  2046.875
0      Laptop  1200.000       1.0  Islamabad  1200.000
3     Monitor   409.375       1.0  Islamabad   409.375
7      Tablet   400.000       1.0    Karachi   400.000
9  Headphones    80.000       2.0     Lahore   160.000
1       Mouse    25.000       2.0     Lahore    50.000
2    Keyboard    45.000       1.0    Karachi    45.000

#### STEP 5: Top Records (IMPORTANT)
### Top 3 Highest Sales

In [22]:
top_sales = df.sort_values(by="total", ascending=False).head(3)
print(top_sales)

      name     price  quantity       city     total
8    Phone   409.375       5.0  Islamabad  2046.875
0   Laptop  1200.000       1.0  Islamabad  1200.000
3  Monitor   409.375       1.0  Islamabad   409.375

#### Lowest Sales

In [23]:
low_sales = df.sort_values(by="total").head(3)
print(low_sales)

         name  price  quantity     city  total
2    Keyboard   45.0       1.0  Karachi   45.0
1       Mouse   25.0       2.0   Lahore   50.0
9  Headphones   80.0       2.0   Lahore  160.0

### STEP 6: Unique Values

In [24]:
print(df["name"].unique())
# Shows all products

['Laptop' 'Mouse' 'Keyboard' 'Monitor' 'Tablet' 'Phone' 'Headphones']

In [25]:
print(df["city"].unique())
# Count unique cities

['Islamabad' 'Lahore' 'Karachi']

### STEP 7: Advanced Filtering
#### Expensive Products in Lahore

In [27]:
result = df[(df["city"] == "Lahore") & (df["price"] > 50)]
print(result)

         name  price  quantity    city  total
9  Headphones   80.0       2.0  Lahore  160.0

#### Laptop Sales Only

In [29]:
print(df[df["name"] == "Laptop"])

     name   price  quantity       city   total
0  Laptop  1200.0       1.0  Islamabad  1200.0

### STEP 8: Group Analysis
#### Total Sales per Product

In [31]:
name_sales = df.groupby("name")["total"].sum()
print(name_sales)

name
Headphones     160.000
Keyboard        45.000
Laptop        1200.000
Monitor        409.375
Mouse           50.000
Phone         2046.875
Tablet         400.000
Name: total, dtype: float64

#### Average Price per City

In [32]:
city_avg = df.groupby("city")["price"].mean()
print(city_avg)

city
Islamabad    672.916667
Karachi      222.500000
Lahore        52.500000
Name: price, dtype: float64

#### Count Orders per Product

In [34]:
count = df["name"].value_counts()
print(count)

name
Laptop        1
Mouse         1
Keyboard      1
Monitor       1
Tablet        1
Phone         1
Headphones    1
Name: count, dtype: int64

### STEP 7: Business Insights
Now think like a company:
### Question 1:

👉 Which product sells the most?

In [35]:
print(df.groupby("name")["quantity"].sum())

name
Headphones    2.0
Keyboard      1.0
Laptop        1.0
Monitor       1.0
Mouse         2.0
Phone         5.0
Tablet        1.0
Name: quantity, dtype: float64

### Question 2:

👉 Which city generates highest revenue?

In [36]:
print(df.groupby("city")["total"].sum().sort_values(ascending=False))

city
Islamabad    3656.25
Karachi       445.00
Lahore        210.00
Name: total, dtype: float64

### Question 3:

👉 Who is the top customer?

In [37]:
print(df.sort_values(by="total", ascending=False).head(1))

    name    price  quantity       city     total
8  Phone  409.375       5.0  Islamabad  2046.875

### PROJECT (CLEAN + ANALYSIS)

In [38]:
import pandas as pd

# Load data
df = pd.read_csv("sales_data.csv")

# Cleaning
df["price"].fillna(df["price"].mean(), inplace=True)
df["quantity"].fillna(1, inplace=True)
df = df.drop_duplicates()
df = df.dropna(subset=["name"])

# Feature engineering
df["total"] = df["price"] * df["quantity"]

# Sorting
print("\n Top Sales:")
print(df.sort_values(by="total", ascending=False).head(3))

# Product analysis
print("\n Product Sales:")
print(df.groupby("name")["total"].sum())

# City analysis
print("\n City Revenue:")
print(df.groupby("city")["total"].sum())

# Most sold product
print("\n Most Sold Product:")
print(df["name"].value_counts())

# Top customer
print("\n Top Customer:")
print(df.sort_values(by="total", ascending=False).head(1))

 Top Sales:
      name     price  quantity       city     total
8    Phone   409.375       5.0  Islamabad  2046.875
0   Laptop  1200.000       1.0  Islamabad  1200.000
3  Monitor   409.375       1.0  Islamabad   409.375

 Product Sales:
name
Headphones     160.000
Keyboard        45.000
Laptop        1200.000
Monitor        409.375
Mouse           50.000
Phone         2046.875
Tablet         400.000
Name: total, dtype: float64

 City Revenue:
city
Islamabad    3656.25
Karachi       445.00
Lahore        210.00
Name: total, dtype: float64

 Most Sold Product:
name
Laptop        1
Mouse         1
Keyboard      1
Monitor       1
Tablet        1
Phone         1
Headphones    1
Name: count, dtype: int64

 Top Customer:
    name    price  quantity       city     total
8  Phone  409.375       5.0  Islamabad  2046.875

/tmp/ipykernel_1351/2185809542.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["price"].fillna(df["price"].mean(), inplace=True)
/tmp/ipykernel_1351/2185809542.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["quantity"].fillna(1, inplace=True)