## Topic: Exploratory Data Analysis (EDA)
### Why EDA is VERY IMPORTANT

👉 Before building models or reports, you must:
- Understand the data
- Find patterns
- Detect problems
- Discover insights

👉 This process is called:
- Exploratory Data Analysis (EDA)

### STEP 1 — Import Pandas & Create Dataset

In [1]:
# Import pandas
import pandas as pd

# Create employee dataset
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Zain", "Ayesha", "Bilal"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [50000, 60000, 45000, 70000, 80000, 55000],
    "Age": [25, 30, 22, 28, 35, 27]
}

# Convert dictionary → DataFrame
df = pd.DataFrame(data)

# Display dataset
df

     Name Department  Salary  Age
0     Ali         IT   50000   25
1   Ahmed         HR   60000   30
2    Sara         IT   45000   22
3    Zain    Finance   70000   28
4  Ayesha         HR   80000   35
5   Bilal         IT   55000   27

### STEP 2 — Basic Data Overview

These commands help you understand structure of data.

In [2]:
# Show first 5 rows
df.head()

     Name Department  Salary  Age
0     Ali         IT   50000   25
1   Ahmed         HR   60000   30
2    Sara         IT   45000   22
3    Zain    Finance   70000   28
4  Ayesha         HR   80000   35

In [3]:
# Show last 5 rows
df.tail()

     Name Department  Salary  Age
1   Ahmed         HR   60000   30
2    Sara         IT   45000   22
3    Zain    Finance   70000   28
4  Ayesha         HR   80000   35
5   Bilal         IT   55000   27

In [4]:
# Number of rows and columns
df.shape

(6, 4)

In [5]:
# Column names
df.columns

Index(['Name', 'Department', 'Salary', 'Age'], dtype='object')

In [6]:
# Complete dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Salary      6 non-null      int64
 3   Age         6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

👉 From this you learn:
- How many rows?
- Which columns?
- Data types?
- Missing values?

### STEP 3 — Statistical Summary

In [7]:
# Summary statistics for numeric columns
df.describe()

            Salary        Age
count      6.00000   6.000000
mean   60000.00000  27.833333
std    13038.40481   4.445972
min    45000.00000  22.000000
25%    51250.00000  25.500000
50%    57500.00000  27.500000
75%    67500.00000  29.500000
max    80000.00000  35.000000

You get:
- Mean salary
- Min / Max salary
- Average age
- Standard deviation
### STEP 4 — Check Unique Values (Categorical Analysis)
#### Unique departments

In [8]:
df["Department"].unique()

array(['IT', 'HR', 'Finance'], dtype=object)

#### Count employees in each department

In [9]:
df["Department"].value_counts()

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

👉 Helps answer:

Which department has more employees?

### STEP 5 — Analyze Relationships
Average salary per department

In [10]:
df.groupby("Department")["Salary"].mean()

Department
Finance    70000.0
HR         70000.0
IT         50000.0
Name: Salary, dtype: float64

#### Highest salary in company

In [11]:
df["Salary"].max()

80000

### Lowest salary in company

In [12]:
df["Salary"].min()

45000

### STEP 6 — Find Business Insights
#### Which department pays the most?

In [13]:
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
Finance    70000.0
HR         70000.0
IT         50000.0
Name: Salary, dtype: float64

#### Youngest employee

In [14]:
df.sort_values("Age").head(1)

   Name Department  Salary  Age
2  Sara         IT   45000   22

#### Oldest employee

In [15]:
df.sort_values("Age", ascending=False).head(1)

     Name Department  Salary  Age
4  Ayesha         HR   80000   35

### Employees per department

In [16]:
df["Department"].value_counts()

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

### STEP 7 — Correlation (Numbers Relationship)

In [17]:
# Correlation between numeric columns
df.corr(numeric_only=True)

          Salary       Age
Salary  1.000000  0.914292
Age     0.914292  1.000000

👉 Shows relationship between:
- Age vs Salary

Value meaning:
- Close to 1 → strong positive relation
- Close to -1 → strong negative relation
- Close to 0 → no relation

### STEP 8 — Detect Outliers

Find unusually high salaries.

In [18]:
# Sort by salary (highest first)
df.sort_values("Salary", ascending=False)

     Name Department  Salary  Age
4  Ayesha         HR   80000   35
3    Zain    Finance   70000   28
1   Ahmed         HR   60000   30
5   Bilal         IT   55000   27
0     Ali         IT   50000   25
2    Sara         IT   45000   22

This helps spot:
- Highest paid employee
- Possible outliers