## Topic: Data Cleaning & Preprocessing (Real-World Data Handling)
### Learning Objectives

By the end of today, you will:

- Handle missing data
- Remove duplicates
- Fix data types
- Detect & treat outliers
- Prepare clean data for Machine Learning

### Step 0 — Import Libraries

In [1]:
# Pandas → data handling
import pandas as pd

# Numpy → numerical operations
import numpy as np

### Step 1 — Create Practice Dataset (Given Task)

We will create the dataset.

In [2]:
# Create messy dataset
data = {
    "age": [25, 30, None, 22, 30],
    "salary": [50000, 60000, 700000, 52000, None],
    "city": ["Lahore", "Karachi", None, "Islamabad", "Lahore"]
}

df = pd.DataFrame(data)

# Show dataset
df

    age    salary       city
0  25.0   50000.0     Lahore
1  30.0   60000.0    Karachi
2   NaN  700000.0       None
3  22.0   52000.0  Islamabad
4  30.0       NaN     Lahore

Notice problems
- Missing values
- Possible outlier (700000 salary)
### Step 2 — Basic Data Inspection

Always inspect before cleaning.

In [3]:
# Info about dataset
df.info()

# Statistical summary
df.describe()

# Count missing values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      float64
 1   salary  4 non-null      float64
 2   city    4 non-null      object
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes

age       1
salary    1
city      1
dtype: int64

### Step 3 — Handle Missing Values
#### 👉 Fill numerical column with MEAN

In [4]:
# Fill missing values in age with average age
df["age"].fillna(df["age"].mean(), inplace=True)

# Fill missing salary with average salary
df["salary"].fillna(df["salary"].mean(), inplace=True)

/tmp/ipykernel_5882/3874531797.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipykernel_5882/3874531797.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["salary"].fillna(df["salary"].mean(), inplace=True)

### Fill categorical column with MODE / label

In [5]:
# Replace missing city with "Unknown"
df["city"].fillna("Unknown", inplace=True)

df

/tmp/ipykernel_5882/2033216820.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["city"].fillna("Unknown", inplace=True)

     age    salary       city
0  25.00   50000.0     Lahore
1  30.00   60000.0    Karachi
2  26.75  700000.0    Unknown
3  22.00   52000.0  Islamabad
4  30.00  215500.0     Lahore

### Step 4 — Remove Duplicates

In [6]:
# Remove duplicate rows (if any)
df = df.drop_duplicates()

df

     age    salary       city
0  25.00   50000.0     Lahore
1  30.00   60000.0    Karachi
2  26.75  700000.0    Unknown
3  22.00   52000.0  Islamabad
4  30.00  215500.0     Lahore

### Step 5 — Fix Data Types

After filling missing values, convert age to integer.

In [7]:
# Convert age from float → int
df["age"] = df["age"].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     5 non-null      int64
 1   salary  5 non-null      float64
 2   city    5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

### Step 6 — Detect Outliers (IQR Method)

We check outliers in salary column.

In [8]:
# Calculate quartiles
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Define lower & upper limits
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Show outliers
outliers = df[(df["salary"] < lower) | (df["salary"] > upper)]
outliers

   age    salary     city
2   26  700000.0  Unknown

You will see 700000 as outlier

### Step 7 — Remove Outliers

In [9]:
# Keep only normal salary values
df = df[(df["salary"] >= lower) & (df["salary"] <= upper)]

df

   age    salary       city
0   25   50000.0     Lahore
1   30   60000.0    Karachi
3   22   52000.0  Islamabad
4   30  215500.0     Lahore

Now dataset is clean

### Step 8 — Convert Categorical Data → Numbers

ML models don’t understand text.

In [10]:
# Convert city column to numbers using one-hot encoding
df = pd.get_dummies(df, columns=["city"], drop_first=True)

df

   age    salary  city_Karachi  city_Lahore
0   25   50000.0         False         True
1   30   60000.0          True        False
3   22   52000.0         False        False
4   30  215500.0         False         True

### Step 9 — Feature Scaling (Very Important)

Bring salary to same scale.

In [11]:
from sklearn.preprocessing import StandardScaler

# Create scaler object
scaler = StandardScaler()

# Scale salary column
df["salary"] = scaler.fit_transform(df[["salary"]])

df

   age    salary  city_Karachi  city_Lahore
0   25 -0.633643         False         True
1   30 -0.490850          True        False
3   22 -0.605084         False        False
4   30  1.729577         False         True

### Step 10 — Final Clean Data Check

In [12]:
# Check missing values again
df.isnull().sum()

# Final dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           4 non-null      int64
 1   salary        4 non-null      float64
 2   city_Karachi  4 non-null      bool
 3   city_Lahore   4 non-null      bool
dtypes: bool(2), float64(1), int64(1)
memory usage: 104.0 bytes

Dataset is now ML ready

### Questions:

#### Q1 — What is data cleaning?
Fixing/removing incorrect or missing data.

#### Q2 — Handling missing values?
Drop rows
Fill with mean/median/mode

#### Q3 — Outliers?
Extreme values that affect analysis.

### Q4 — Feature scaling?
Brings all features to same scale for ML.