## Topic: Introduction to Pandas
### What is Pandas?

👉 A Python library used for:
- Data analysis
- Data manipulation

### What is Pandas?

👉 A Python library used for:
- Data analysis
- Data manipulation
### STEP 1 — Import Pandas

Create a new Colab notebook and run:

In [1]:
import pandas as pd

### STEP 2 — Create Your Own Dataset

We will create a Student dataset (easy to understand).

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   22

In [3]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Fatima", "Usman", "Ayesha", "Bilal", "Zain"],
    "Age": [21, 22, 20, 23, 24, 21, 22, 23],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Marks": [85, 90, 78, 88, 92, 95, 80, 87]
}

df = pd.DataFrame(data)
df

     Name  Age       City  Marks
0     Ali   21     Lahore     85
1   Ahmed   22    Karachi     90
2    Sara   20  Islamabad     78
3  Fatima   23     Lahore     88
4   Usman   24    Karachi     92
5  Ayesha   21  Islamabad     95
6   Bilal   22     Lahore     80
7    Zain   23    Karachi     87

 This creates a DataFrame (table).

### STEP 3 — Save Dataset as CSV (Important for Task)

Now we save it as a CSV file.

In [4]:
df.to_csv("students.csv", index=False)

Now your dataset is stored in Colab storage.

### STEP 4 — Load CSV using Pandas

This matches your task requirement

In [5]:
df = pd.read_csv("students.csv")
df

     Name  Age       City  Marks
0     Ali   21     Lahore     85
1   Ahmed   22    Karachi     90
2    Sara   20  Islamabad     78
3  Fatima   23     Lahore     88
4   Usman   24    Karachi     92
5  Ayesha   21  Islamabad     95
6   Bilal   22     Lahore     80
7    Zain   23    Karachi     87

### STEP 5 — Print First 5 Rows

In [6]:
df.head()

     Name  Age       City  Marks
0     Ali   21     Lahore     85
1   Ahmed   22    Karachi     90
2    Sara   20  Islamabad     78
3  Fatima   23     Lahore     88
4   Usman   24    Karachi     92

Output shows first 5 rows of dataset.

### STEP 6 — Show Summary Statistics

This is VERY IMPORTANT function

In [7]:
df.describe()

             Age     Marks
count   8.000000   8.00000
mean   22.000000  86.87500
std     1.309307   5.76783
min    20.000000  78.00000
25%    21.000000  83.75000
50%    22.000000  87.50000
75%    23.000000  90.50000
max    24.000000  95.00000

You will see:
- mean
- min
- max
- std
- quartiles
### STEP 7 — Dataset Information

Extra learning (deep understanding):

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Marks   8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes

Shows:
- number of rows
- column types
- missing values
### STEP 8 — Shape & Columns

In [9]:
df.shape

(8, 4)

 Output → (rows, columns)

In [10]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

### STEP 9 — Select One Column (Task Requirement)

Select Marks column

In [11]:
df["Marks"]

0    85
1    90
2    78
3    88
4    92
5    95
6    80
7    87
Name: Marks, dtype: int64

### Select Row & Specific Value

Row:

In [12]:
df.iloc[0]

Name        Ali
Age          21
City     Lahore
Marks        85
Name: 0, dtype: object

Specific value:

In [13]:
df.loc[0, "Name"]

'Ali'