## Topic: Data Filtering & Sorting (Pandas)
### Why This Topic Matters

In real jobs, you don’t just load data — you:
- Find specific records
- Filter useful information
- Sort data to identify trends

👉 This is used in:
- Data Analyst roles
- Business dashboards
- Machine Learning preprocessing

### STEP 1 — Load Dataset in Colab

In [1]:
# Import pandas library
import pandas as pd

# Create dataset (Employee data)
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Zain", "Ayesha"],
    "Age": [25, 30, 22, 28, 35],
    "Salary": [50000, 60000, 45000, 70000, 80000]
}

# Convert dictionary into DataFrame (table format)
df = pd.DataFrame(data)

# Show dataset
df

     Name  Age  Salary
0     Ali   25   50000
1   Ahmed   30   60000
2    Sara   22   45000
3    Zain   28   70000
4  Ayesha   35   80000

### STEP 2 — Filtering Data (Conditions)
Example 1: Age greater than 25

In [2]:
# Show employees whose Age is greater than 25
df[df["Age"] > 25]

     Name  Age  Salary
1   Ahmed   30   60000
3    Zain   28   70000
4  Ayesha   35   80000

What happens here?
- df["Age"] > 25 creates True/False values
- Pandas shows only rows where condition is True

#### Example 2: Salary greater than 60,000

In [3]:
# Show employees earning more than 60k
df[df["Salary"] > 60000]

     Name  Age  Salary
3    Zain   28   70000
4  Ayesha   35   80000

Real meaning: Find high earners

####  Example 3: Multiple Conditions (AND)

In [4]:
# Employees older than 25 AND salary above 60k
df[(df["Age"] > 25) & (df["Salary"] > 60000)]

     Name  Age  Salary
3    Zain   28   70000
4  Ayesha   35   80000

Important:
- Use & for AND
- Wrap each condition in brackets

#### Example 4: OR Condition

In [5]:
# Employees older than 30 OR salary above 70k
df[(df["Age"] > 30) | (df["Salary"] > 70000)]

     Name  Age  Salary
4  Ayesha   35   80000

Use | for OR

### STEP 3 — Sorting Data
 Sort by Age (Ascending)

In [6]:
# Sort employees by Age (young → old)
df.sort_values("Age")

     Name  Age  Salary
2    Sara   22   45000
0     Ali   25   50000
3    Zain   28   70000
1   Ahmed   30   60000
4  Ayesha   35   80000

Ascending = smallest → largest (default)

#### Sort by Salary (Descending)

In [7]:
# Sort employees by Salary (highest → lowest)
df.sort_values("Salary", ascending=False)

     Name  Age  Salary
4  Ayesha   35   80000
3    Zain   28   70000
1   Ahmed   30   60000
0     Ali   25   50000
2    Sara   22   45000

ascending=False = biggest → smallest

### STEP 4 — Select Specific Columns After Filtering

In [8]:
# Show only Name & Salary where Age > 25
df[df["Age"] > 25][["Name", "Salary"]]

     Name  Salary
1   Ahmed   60000
3    Zain   70000
4  Ayesha   80000

Step breakdown:

1. Filter rows → Age > 25
2. Select columns → Name & Salary

This is very common in real projects

### Real-World Thinking (Important)

Imagine this is company employee data:

You can now:
- Find employees ready for promotion
- Find highest paid employees
- Filter senior staff
- Create HR reports

We just learned real data analysis skills