### Topic: Handling Missing Data (Data Cleaning)
Why This Topic is CRITICAL

👉 In real datasets:
- Data is never clean
- Missing values are everywhere

👉 If you don’t handle them:
- Wrong analysis
- Bad ML models
-  Poor decisions

### STEP 1 — Create Dataset With Missing Values

In [1]:
# Import libraries
import pandas as pd
import numpy as np   # Used to create missing values (NaN)

# Create dataset with missing values
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Zain", "Ayesha"],
    "Age": [25, np.nan, 22, 28, np.nan],      # Missing ages
    "Salary": [50000, 60000, np.nan, 70000, 80000]  # Missing salary
}

# Convert into DataFrame
df = pd.DataFrame(data)

# Display dataset
df

     Name   Age   Salary
0     Ali  25.0  50000.0
1   Ahmed   NaN  60000.0
2    Sara  22.0      NaN
3    Zain  28.0  70000.0
4  Ayesha   NaN  80000.0

np.nan = Missing value in Pandas.

###  STEP 2 — Detect Missing Values
#### Check where values are missing

In [2]:
# Shows True/False for each cell
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False   True   False

True = missing value
False = value exists

#### Count missing values in each column

In [3]:
# Count total missing values column-wise
df.isnull().sum()

Name      0
Age       2
Salary    1
dtype: int64

You will see something like:
- Age → 2 missing
- Salary → 1 missing

### STEP 3 — Remove Missing Values

 Usually NOT best practice, but important to learn.
###  Remove rows that contain ANY missing value

In [4]:
# Drop rows that have at least one NaN
df.dropna()

   Name   Age   Salary
0   Ali  25.0  50000.0
3  Zain  28.0  70000.0

👉 Whole row removed if even one value is missing

####  Remove rows where Age is missing only

In [5]:
# Drop rows where Age is NaN
df.dropna(subset=["Age"])

   Name   Age   Salary
0   Ali  25.0  50000.0
2  Sara  22.0      NaN
3  Zain  28.0  70000.0

👉 Only checks Age column.

### STEP 4 — Fill Missing Values (Best Practice)

 In real projects we fill, not delete.

#### Fill Age with Mean

In [6]:
# Replace missing Age values with average age
df["Age"].fillna(df["Age"].mean(), inplace=True)

df

/tmp/ipykernel_16560/2930511990.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

     Name   Age   Salary
0     Ali  25.0  50000.0
1   Ahmed  25.0  60000.0
2    Sara  22.0      NaN
3    Zain  28.0  70000.0
4  Ayesha  25.0  80000.0

Why mean?

Because Age is numeric data.

###  Fill Salary with Median

In [7]:
# Replace missing Salary with median salary
df["Salary"].fillna(df["Salary"].median(), inplace=True)

df

/tmp/ipykernel_16560/493182924.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].median(), inplace=True)

     Name   Age   Salary
0     Ali  25.0  50000.0
1   Ahmed  25.0  60000.0
2    Sara  22.0  65000.0
3    Zain  28.0  70000.0
4  Ayesha  25.0  80000.0

Why median?

Median works better when outliers exist.

#### Fill With Constant Value (Example)

Sometimes we fill with fixed value.

In [8]:
# Example: Replace any remaining missing Age with 0
df["Age"].fillna(0, inplace=True)

df

/tmp/ipykernel_16560/2306337963.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(0, inplace=True)

     Name   Age   Salary
0     Ali  25.0  50000.0
1   Ahmed  25.0  60000.0
2    Sara  22.0  65000.0
3    Zain  28.0  70000.0
4  Ayesha  25.0  80000.0

(After previous steps, this may not change anything — just for learning)

# 📊 WHEN TO USE WHAT?

| Situation |  Recommended Method |
|:----------|:----------------------|
| **Numeric data** | Mean / Median |
| **Outliers present** | Median |
| **Categorical data** | Mode |
| **Important data missing** |  Do NOT drop rows |

### STEP 5 — Check Again (Final Verification)

In [9]:
# Final check for missing values
df.isnull().sum()

Name      0
Age       0
Salary    0
dtype: int64

Output should be 0 missing values.