## Topic: Removing Duplicates + Data Formatting
### Why This Matters

In real datasets:
- Same record appears multiple times
- Data types are incorrect

👉 If you don’t fix this:
- Wrong analysis
- Misleading insights

### STEP 1 — Create Dataset With Issues

In [1]:
# Import pandas
import pandas as pd

# Dataset contains problems:
# - Duplicate rows
# - Salary stored as string (object) instead of number

data = {
    "Name": ["Ali", "Ahmed", "Sara", "Ali", "Zain"],
    "Age": [25, 30, 22, 25, 28],
    "Salary": ["50000", "60000", "45000", "50000", "70000"]  #  string values
}

df = pd.DataFrame(data)

# Display dataset
df

    Name  Age Salary
0    Ali   25  50000
1  Ahmed   30  60000
2   Sara   22  45000
3    Ali   25  50000
4   Zain   28  70000

### STEP 2 — Check Duplicate Rows

In [2]:
# Shows True/False for duplicate rows
df.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

True means row is duplicated.

#### Count total duplicates

In [3]:
df.duplicated().sum()

np.int64(1)

This tells how many duplicate rows exist.

### STEP 3 — Remove Duplicate Rows

In [5]:
# Remove complete duplicate rows
df = df.drop_duplicates()

df

    Name  Age Salary
0    Ali   25  50000
1  Ahmed   30  60000
2   Sara   22  45000
4   Zain   28  70000

Now identical rows are removed.

### STEP 4 — Remove Duplicates Based on Column

Sometimes we want one record per person.

In [6]:
# Keep only first occurrence of each Name
df = df.drop_duplicates(subset=["Name"])

df

    Name  Age Salary
0    Ali   25  50000
1  Ahmed   30  60000
2   Sara   22  45000
4   Zain   28  70000

Now each name appears only once.

### STEP 5 — Check Data Types

In [7]:
df.dtypes

Name      object
Age        int64
Salary    object
dtype: object

You will notice:

| Column | Type |
|--------|------|
| Name | object |
| Age | int |
| Salary | object  (should be numeric) |

Salary should be numeric.

### STEP 6 — Convert Data Type

In [8]:
# Convert Salary from string → integer
df["Salary"] = df["Salary"].astype(int)

# Verify again
df.dtypes

Name      object
Age        int64
Salary     int64
dtype: object

Now Salary becomes int64

### STEP 7 — Rename Columns (Standard Naming)

Best practice in data science → use lowercase column names.

In [9]:
# Rename columns
df.columns = ["name", "age", "salary"]

df

    name  age  salary
0    Ali   25   50000
1  Ahmed   30   60000
2   Sara   22   45000
4   Zain   28   70000

### STEP 8 — Clean Text Data

Make names consistent (lowercase).

In [10]:
# Convert names to lowercase
df["name"] = df["name"].str.lower()

df

    name  age  salary
0    ali   25   50000
1  ahmed   30   60000
2   sara   22   45000
4   zain   28   70000

Why?
Because "Ali" and "ali" should be treated same.

### STEP 9 — Final Clean Dataset

In [11]:
# Final cleaned dataset
print(df)

    name  age  salary
0    ali   25   50000
1  ahmed   30   60000
2   sara   22   45000
4   zain   28   70000

You now have:
- No duplicates
- Correct data types
- Clean column names
- Consistent text