## Topic: Feature Engineering (Creating New Columns)
### Why This is IMPORTANT

👉 In real-world projects, raw data is not enough.

You need to:
- Create new features
- Transform data
- Make it useful for analysis & ML

👉 This is called:

Feature Engineering (very important in AI & Data Science)

### STEP 1 — Import Pandas

In [1]:
# Import pandas library
import pandas as pd

### STEP 2 — Create Dataset With Problems

Dataset has:
- Duplicate rows
- Salary stored as text

In [2]:
# Create dataset
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Ali", "Zain"],
    "Age": [25, 30, 22, 25, 28],
    "Salary": ["50000", "60000", "45000", "50000", "70000"]  # Salary as string
}

# Convert into DataFrame
df = pd.DataFrame(data)

# Show dataset
df

    Name  Age Salary
0    Ali   25  50000
1  Ahmed   30  60000
2   Sara   22  45000
3    Ali   25  50000
4   Zain   28  70000

### STEP 3 — Detect Duplicate Rows

In [3]:
# Check which rows are duplicates (True = duplicate)
df.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

####  Count total duplicate rows

In [4]:
# Count number of duplicate rows
df.duplicated().sum()

np.int64(1)

### STEP 4 — Remove Duplicate Rows

#### VERY IMPORTANT CONCEPT
 Wrong
 ```
 df.drop_duplicates()
 ```
 Correct

We must assign back to dataframe.
```
# Remove complete duplicate rows
df = df.drop_duplicates()

df
```

In [5]:
# Remove complete duplicate rows
df = df.drop_duplicates()

df

    Name  Age Salary
0    Ali   25  50000
1  Ahmed   30  60000
2   Sara   22  45000
4   Zain   28  70000

### STEP 5 — Remove Duplicates Based on Name Only

Sometimes we want one record per person.

In [6]:
# Keep first occurrence of each Name only
df = df.drop_duplicates(subset=["Name"])

df

    Name  Age Salary
0    Ali   25  50000
1  Ahmed   30  60000
2   Sara   22  45000
4   Zain   28  70000

Now each employee appears once

### STEP 6 — Check Data Types

In [7]:
# Check column data types
df.dtypes

Name      object
Age        int64
Salary    object
dtype: object

You will see:

Salary → object  (string)

We need numeric type for calculations.
### STEP 7 — Convert Salary to Integer

In [8]:
# Convert Salary from string to integer
df["Salary"] = df["Salary"].astype(int)

# Verify conversion
df.dtypes

Name      object
Age        int64
Salary     int64
dtype: object

Now Salary is numeric

### STEP 8 — Rename Columns to Lowercase
- Best practice in data science:
- Column names should be lowercase.

In [9]:
# Rename columns
df.columns = ["name", "age", "salary"]

df

    name  age  salary
0    Ali   25   50000
1  Ahmed   30   60000
2   Sara   22   45000
4   Zain   28   70000

### STEP 9 — Clean Text Data (Standardization)

Why?

"Ali" and "ali" should be same.

In [10]:
# Convert names to lowercase
df["name"] = df["name"].str.lower()

df

    name  age  salary
0    ali   25   50000
1  ahmed   30   60000
2   sara   22   45000
4   zain   28   70000

### STEP 10 — Final Clean Dataset

In [11]:
# Final cleaned dataset
print(df)

    name  age  salary
0    ali   25   50000
1  ahmed   30   60000
2   sara   22   45000
4   zain   28   70000