## Topic: GroupBy Operations (Core Data Analysis Skill)
###  Why GroupBy is VERY IMPORTANT

👉 This is used in:
- Business reports
- Dashboards
- Data Analyst jobs

👉 It helps you answer questions like:
- Total sales by category
- Average salary by department
- Count of employees by group

### STEP 1 — Import Pandas & Create Dataset

In [1]:
# Import pandas
import pandas as pd

# Create employee dataset
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Zain", "Ayesha", "Bilal"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [50000, 60000, 45000, 70000, 80000, 55000]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Show dataset
df

     Name Department  Salary
0     Ali         IT   50000
1   Ahmed         HR   60000
2    Sara         IT   45000
3    Zain    Finance   70000
4  Ayesha         HR   80000
5   Bilal         IT   55000

### STEP 2 — Basic GroupBy

In [2]:
# Create groups based on Department
df.groupby("Department")

👉 This only creates groups internally.

To see results, we must apply aggregation (mean, sum, count).

### STEP 3 — Aggregation Functions
#### Average Salary by Department

In [3]:
# Mean salary for each department
df.groupby("Department")["Salary"].mean()

Department
Finance    70000.0
HR         70000.0
IT         50000.0
Name: Salary, dtype: float64

This answers:

👉 Which department pays average salary highest?

####  Total Salary by Department

In [4]:
# Total salary spent per department
df.groupby("Department")["Salary"].sum()

Department
Finance     70000
HR         140000
IT         150000
Name: Salary, dtype: int64

This answers:

👉 How much company spends per department

#### Count Employees per Department

In [5]:
# Count number of employees in each department
df.groupby("Department")["Name"].count()

Department
Finance    1
HR         2
IT         3
Name: Name, dtype: int64

This answers:

👉 How many employees in each department

#### STEP 4 — Multiple Aggregations Together

In [6]:
# Apply multiple statistics at once
df.groupby("Department")["Salary"].agg(["mean", "sum", "max", "min"])

               mean     sum    max    min
Department
Finance     70000.0   70000  70000  70000
HR          70000.0  140000  80000  60000
IT          50000.0  150000  55000  45000

You get:
- Average salary
- Total salary
- Highest salary
- Lowest salary

This is very common in dashboards

### STEP 5 — Reset Index (Clean Table Output)

GroupBy makes Department an index.

We convert it back to normal column.

In [7]:
# Convert result back to normal table format
df.groupby("Department")["Salary"].mean().reset_index()

  Department   Salary
0    Finance  70000.0
1         HR  70000.0
2         IT  50000.0

Now output looks like a proper table

### STEP 6 — GroupBy Multiple Columns

In [8]:
# Group by Department AND Salary
df.groupby(["Department", "Salary"]).count()

                   Name
Department Salary
Finance    70000      1
HR         60000      1
           80000      1
IT         45000      1
           50000      1
           55000      1

This creates multi-level grouping.

Used in advanced reports.
### STEP 7 — Real-World Insight Example
####Find Highest Paying Department

In [9]:
# Sort departments by average salary (highest first)
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
Finance    70000.0
HR         70000.0
IT         50000.0
Name: Salary, dtype: float64

This answers real business question:

👉 Which department pays the most?