## Topic: Merging & Joining DataFrames
#### Why This is VERY IMPORTANT

👉 In real-world projects:
- Data is stored in multiple tables/files
- You must combine them

👉 Just like SQL JOINs:
- Customer data + Orders
- Employees + Salaries

### STEP 1 — Import Pandas & Create Two Datasets

In [1]:
# Import pandas
import pandas as pd

# Employees table (like Employees.csv)
employees = pd.DataFrame({
    "Emp_ID": [1, 2, 3, 4],
    "Name": ["Ali", "Ahmed", "Sara", "Zain"],
    "Department": ["IT", "HR", "Finance", "IT"]
})

# Salaries table (like Salaries.csv)
salaries = pd.DataFrame({
    "Emp_ID": [1, 2, 3, 5],
    "Salary": [50000, 60000, 70000, 80000]
})

# Display both datasets
employees, salaries

(   Emp_ID   Name Department
 0       1    Ali         IT
 1       2  Ahmed         HR
 2       3   Sara    Finance
 3       4   Zain         IT,
    Emp_ID  Salary
 0       1   50000
 1       2   60000
 2       3   70000
 3       5   80000)

👉 Real world: data usually comes from different files/tables.

### STEP 2 — INNER JOIN (Common Records Only)

In [2]:
# Merge where Emp_ID exists in BOTH tables
merged = pd.merge(employees, salaries, on="Emp_ID", how="inner")

merged

   Emp_ID   Name Department  Salary
0       1    Ali         IT   50000
1       2  Ahmed         HR   60000
2       3   Sara    Finance   70000

Explanation:
- Emp_ID 1,2,3 exist in both → kept
- Emp_ID 4 & 5 removed (not common)
### STEP 3 — LEFT JOIN (Keep All Employees)

In [3]:
# Keep ALL employees, even if salary missing
left_join = pd.merge(employees, salaries, on="Emp_ID", how="left")

left_join

   Emp_ID   Name Department   Salary
0       1    Ali         IT  50000.0
1       2  Ahmed         HR  60000.0
2       3   Sara    Finance  70000.0
3       4   Zain         IT      NaN

👉 Employee with Emp_ID=4 has no salary → NaN

This is VERY common in real datasets.

### STEP 4 — RIGHT JOIN (Keep All Salaries)

In [4]:
# Keep ALL salary records
right_join = pd.merge(employees, salaries, on="Emp_ID", how="right")

right_join

   Emp_ID   Name Department  Salary
0       1    Ali         IT   50000
1       2  Ahmed         HR   60000
2       3   Sara    Finance   70000
3       5    NaN        NaN   80000

👉 Emp_ID=5 appears even though employee data missing.

### STEP 5 — OUTER JOIN (Keep EVERYTHING)

In [5]:
# Keep all rows from both tables
outer_join = pd.merge(employees, salaries, on="Emp_ID", how="outer")

outer_join

   Emp_ID   Name Department   Salary
0       1    Ali         IT  50000.0
1       2  Ahmed         HR  60000.0
2       3   Sara    Finance  70000.0
3       4   Zain         IT      NaN
4       5    NaN        NaN  80000.0

This shows complete combined dataset.

### STEP 6 — Handle Missing Values After Merge
- After LEFT JOIN we saw NaN.
- We often replace missing values.

In [6]:
# Replace NaN with 0
left_join.fillna(0, inplace=True)

left_join

   Emp_ID   Name Department   Salary
0       1    Ali         IT  50000.0
1       2  Ahmed         HR  60000.0
2       3   Sara    Finance  70000.0
3       4   Zain         IT      0.0

### STEP 7 — REAL WORLD ANALYSIS

👉 Total Salary by Department

##### First merge tables again:

In [7]:
# Merge employees and salaries (inner join)
merged = pd.merge(employees, salaries, on="Emp_ID", how="inner")

merged

   Emp_ID   Name Department  Salary
0       1    Ali         IT   50000
1       2  Ahmed         HR   60000
2       3   Sara    Finance   70000

#### Now perform analysis:

In [8]:
# Total salary spent per department
merged.groupby("Department")["Salary"].sum()

Department
Finance    70000
HR         60000
IT         50000
Name: Salary, dtype: int64

### Business question answered:

How much company spends per department